#!/usr/bin/env python3
"""
DAMbv InfraDrone — Solar Panel Inspection Report Generator
Usage: python3 generate_solar_report.py <input_json> <output_pdf>
"""
import sys, json
from datetime import datetime
from collections import Counter
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER

BRAND_BLUE = colors.HexColor('#1A4A8A')
BRAND_GREEN = colors.HexColor('#0D9E75')
BRAND_GRAY = colors.HexColor('#64748b')
LIGHT_GRAY = colors.HexColor('#f1f5f9')
SEVERITY_COLORS = {
    "Critical": colors.HexColor('#dc2626'),
    "High": colors.HexColor('#ea580c'),
    "Medium": colors.HexColor('#eab308'),
    "Low": colors.HexColor('#0d9e75'),
    "None": colors.HexColor('#64748b'),
    "Unknown": colors.HexColor('#94a3b8'),
}

def generate(input_path, out_path):
    with open(input_path) as f:
        data = json.load(f)
    results = data["results"]

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle('h1', parent=styles['Heading1'], textColor=BRAND_BLUE, fontSize=18)
    h2 = ParagraphStyle('h2', parent=styles['Heading2'], textColor=BRAND_BLUE, fontSize=13)
    body = ParagraphStyle('body', parent=styles['Normal'], fontSize=10, leading=14)

    doc = SimpleDocTemplate(out_path, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm, leftMargin=20*mm, rightMargin=20*mm)
    story = []

    story.append(Paragraph('DAMbv InfraDrone', h1))
    story.append(Paragraph('Solar Panel Inspection Report', styles['Normal']))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_BLUE, spaceBefore=6, spaceAfter=12))

    severity_counts = Counter(r["Severity"] for r in results)
    total = len(results)
    flagged = total - severity_counts.get("None", 0)

    story.append(Paragraph('Summary', h2))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_GRAY, spaceAfter=6))
    summary_rows = [['Metric', 'Value'],
                     ['Panels inspected', str(total)],
                     ['Panels flagged with an anomaly', str(flagged)],
                     ['Critical', str(severity_counts.get('Critical', 0))],
                     ['High', str(severity_counts.get('High', 0))],
                     ['Medium', str(severity_counts.get('Medium', 0))],
                     ['Low (routine maintenance)', str(severity_counts.get('Low', 0))]]
    story.append(Table(summary_rows, colWidths=[90*mm, 80*mm], style=TableStyle([
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('BACKGROUND', (0,0), (-1,0), LIGHT_GRAY),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('TOPPADDING', (0,0), (-1,-1), 4), ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ])))
    story.append(Spacer(1, 16))

    story.append(Paragraph('Panel-by-Panel Findings (highest priority first)', h2))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_GRAY, spaceAfter=6))
    finding_rows = [['Image', 'Finding', 'Confidence', 'Severity']]
    for r in results:
        if r["Severity"] == "None":
            continue
        finding_rows.append([
            r["ImagePath"].split("/")[-1],
            r["Label"],
            f"{r['Confidence']*100:.0f}%",
            r["Severity"]
        ])
    if len(finding_rows) == 1:
        finding_rows.append(["-", "No anomalies detected", "-", "-"])
    story.append(Table(finding_rows, colWidths=[55*mm, 45*mm, 30*mm, 30*mm], style=TableStyle([
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('BACKGROUND', (0,0), (-1,0), LIGHT_GRAY),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('TOPPADDING', (0,0), (-1,-1), 3), ('BOTTOMPADDING', (0,0), (-1,-1), 3),
    ])))
    story.append(Spacer(1, 16))

    story.append(Paragraph('Model Information', h2))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_GRAY, spaceAfter=6))
    story.append(Paragraph(
        f"Classifications generated by a real trained CNN (RaptorMaps InfraredSolarModules "
        f"public dataset, 12 defect classes). Model accuracy: {data.get('model_accuracy', 'unknown')}. "
        f"This is a real, working first-generation model -- flagged findings should be visually "
        f"confirmed before action is taken, not treated as certain.", body))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", body))

    doc.build(story)
    print(f"Report generated: {out_path}")

if __name__ == "__main__":
    generate(sys.argv[1], sys.argv[2])
